"""add favorite files

Revision ID: bcf48d92325d
Revises: e5e0926fa01f
Create Date: 2026-07-31 23:44:55.287518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf48d92325d'
down_revision: Union[str, Sequence[str], None] = 'e5e0926fa01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "files",
        sa.Column(
            "is_favorite",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column(
        "files",
        "is_favorite",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_favorite')
    # ### end Alembic commands ###
